--Creacion tabla temporal
create table "unique".Temporal (
 	NOMBRE_CLIENTE text,
 	CORREO_CLIENTE text,
 	CLIENTE_ACTIVO text,
 	FECHA_CREACION date,
 	TIENDA_PREFERIDA text,
 	DIRECCION_CLIENTE text,
 	CODIGO_POSTAL int,
 	CIUDAD_CLIENTE text,
 	PAIS_CLIENTE text,
 	FECHA_RENTA timestamp,
 	FECHA_RETORNO timestamp,
 	MONTO_A_PAGAR float,
 	FECHA_PAGO timestamp,
 	NOMBRE_EMPLEADO text,
 	CORREO_EMPLEADO text,
 	EMPLEADO_ACTIVO text,
 	TIENDA_EMPLEADO text,
 	USUARIO_EMPLEADO text,
 	CONTRASENA_EMPLEADO text,
 	DIRECCION_EMPLEADO text,
 	CODIGO_POSTAL_EMPLEADO int,
 	CIUDAD_EMPLEADO text,
 	PAIS_EMPLEADO text,
 	NOMBRE_TIENDA text,
 	ENCARGADO_TIENDA text,
 	DIRECCION_TIENDA text,
 	CODIGO_POSTAL_TIENDA int,
 	CIUDAD_TIENDA text,
 	PAIS_TIENDA text,
 	TIENDA_PELICULA text,
 	NOMBRE_PELICULA text,
 	DESCRIPCION_PELICULA text,
 	ANO_LANZAMIENTO int,
 	DIAS_RENTA int,
 	COSTO_RENTA float,
 	DURACION int,
 	COSTO_POR_DANO float,
 	CLASIFICACION text,
 	LENGUAJE_PELICULA text,
 	CATEGORIA_PELICULA text,
 	ACTOR_PELICULA text
);

COPY "unique".Temporal from '/home/josee/Documents/Archivos/Practica/BlockbusterData.csv' with DELIMITER ';' NULL '-' CSV HEADER ENCODING 'latin-1';
TRUNCATE "unique".temporal;